{
 "title": "Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"${namespace}\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(kube_pod_container_status_restarts_total{namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"${namespace}\", container!=\"\", container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container!=\"POD\", container!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"node-service\"}",
     "legendFormat": "Current pods"
    }
   ]
  },
  {
   "title": "Node-service HPA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"node-service\"} / kube_hpa_spec_max_replicas{hpa=\"node-service\"}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"default\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum (node_service_timeout_seconds_bucket{kubernetes_namespace=\"${namespace}\"}) by (le))",
     "legendFormat": "0.9 percentile"
    },
    {
     "expr": "histogram_quantile(0.2, sum (node_service_timeout_seconds_bucket{kubernetes_namespace=\"${namespace}\"}) by (le))",
     "legendFormat": "0.5 percentile"
    }
   ]
  }
 ]
}