---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
 name: node-service
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: node-service
 minReplicas: 2
 maxReplicas: 4
 behavior:
  scaleDown:
    stabilizationWindowSeconds: 60
 metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 60m
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 90Mi