apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
    chart: angular-app
    release: angular-app
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
      release: angular-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: angular-app
        release: angular-app
    spec:
      containers:
        - name: angular-app
          image: sanzmiguel/angular-app:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 100Mi
            requests:
              cpu: 70m
              memory: 40Mi